### ISSUE TITLE
Is there a Perl 7 discussion happening? / Invariant-sigil article proposal

### ISSUE THREAD

**Issue by cxw42** [tpf/perldotcom#205]
I don't know where else to ask since I don't currently have bandwidth to drink from the p5p firehose :)  -  perl6/problem-solving#81 and  perl6/problem-solving#89 have given rise to at least one [suggestion](http://blogs.perl.org/users/ovid/2019/08/is-perl-6-being-renamed.html#comment-1807539) (**edit** and https://github.com/perl6/problem-solving/issues/81#issuecomment-526856296 , **but see** lizmat's https://github.com/perl6/problem-solving/issues/81#issuecomment-527592817 for additional thoughts) that P5 should bump to v7 when P6 switches to Raku (assuming it does).  I checked GH, general searches, and p5p archives, but haven't found any extended discussion of what that would look like (just a few comments on the linked).  Most of the "Perl 7" hits I found are from 2012/2013.  Could someone point me to a current discussion if it's happening?

If there is not an existing conversation, I would like to write an article for perl.com proposing that invariant sigils would be a good way to justify a major-version bump, and exploring some of the details and consequences.  Would that be of any interest to the editors?

Thanks!

**Comment by duncand** [comment]
Were Perl to change its versioning formally from 5.X to X the most reasonable way would be to take the current minor version and make it the major, so Perl version 30.0 would be the current one, Perl version 32.0 would be next year's, and so on.  If you do a "perl -v" then "version 30" is how it is already reported to users, and mainly what's left is supporting saying "use 30" and such.

**Comment by duncand** [comment]
Generally speaking there is little benefit in having a Perl 5 versioning discussion now.  Waiting first to see how the Perl 6 renaming works out and acting only after that is settled, is best.

**Comment by dnmfarrell** [comment]
Hi @cxw42 

> If there is not an existing conversation, I would like to write an article for perl.com proposing that invariant sigils would be a good way to justify a major-version bump, and exploring some of the details and consequences. Would that be of any interest to the editors?

This sounds like a great idea - framing it as "here's a cool feature I'd like the next major version of perl to have" would sidestep the versioning discussion I think.

**Comment by cxw42** [comment]
@dnmfarrell Sounds good!  I will work towards a draft early in October.

@duncand `use v30` is fine with me :)

**Comment by JendaPerl** [comment]
I don't much care how does the renaming of the thing that was originally supposed to be Perl 6 work out, but I do agree that it's way too early to speak about changing the version of actual Perl. 
One step at a time, otherwise the confusion gets too big. Once Perl 6 gets renamed to whatever they agree on, websites, links and docs get updated and the situation had a chance to settle down, then it's going to be a time to discuss whether it's gonna be 7.0 or 30 or 32 or whatever.
The 32 being 2 to the power of 5 could be used in the marketing though ... ;-)

**Comment by yuki-kimoto** [comment]
I aslo think it is good to wait for finishing Perl 6 to Raku renaming discussion.

**Comment by lizmat** [comment]
Just for the record:

>  that P5 should bump to v7

I'm quite unclear how you go from https://github.com/perl6/problem-solving/issues/81#issuecomment-527592817 to "P5 **should** bump to v7".  The only thing I stated was that **IF** p5p **would** decide that, then **that** would be a clear message.  I have in no way intended that they should.  And also, I think that **IF** p5p would decide anything, "Perl 32" would make a **lot** more sense to me, especially since earlier discussions about "Perl 7" could be considered tainted.

**Comment by cxw42** [comment]
@lizmat Sorry for the confusion - I cited your comment as a counterpoint.  I have edited my original post to (hopefully) clarify.  Thanks for circling back!

**Comment by dnmfarrell** [comment]
@cxw42 can we close this issue as your question was answered?

**Comment by cxw42** [comment]
@dnmfarrell Sure - I was planning to close it in the PR with the article, but I have no objection to closing it sooner.
