### ISSUE TITLE
Draft for "Searching Internet RFCs"

### ISSUE THREAD

**Issue by briandfoy** [tpf/perldotcom#275]
@Baseband-processor: I've added your RFC Search article in the [briandfoy/rfc_search](https://github.com/tpf/perldotcom/tree/briandfoy/rfc_search) branch at [content/article/searching-internet-rfcs.md](https://github.com/tpf/perldotcom/blob/briandfoy/rfc_search/content/article/searching-internet-rfcs.md). See if you like it. 

I'd still like to get a more personal story about an RFC that interested you and what you learned from it, and so on.

I still want to do a little work on it, and I'm making a small screencast of the program running.

**Comment by Baseband-processor** [comment]
Hi Brian.
already modified everything,
check if you like it.
Regards
Edoardo Mantovani, 2020

Il giorno mar 15 set 2020 alle ore 18:44 brian d foy <
notifications@github.com> ha scritto:

**Comment by briandfoy** [comment]
Are you saying that you have nothing to add to the article? Is everything you've added in the file that I committed?

**Comment by Baseband-processor** [comment]
For now yes,
I though I've added new parts, if you are interested in other parts let me
know and I'll modify right now the article.

Regards
Edoardo Mantovani, 2020

Il giorno mar 15 set 2020 alle ore 19:50 brian d foy <
notifications@github.com> ha scritto:

**Comment by briandfoy** [comment]
If anything is missing, let's re-add that.

**Comment by Baseband-processor** [comment]
a good step would be to accept the modification.
Regards
Edoardo Mantovani, 2020

**Comment by briandfoy** [comment]
Hey @Baseband-processor, did you ever provide us an author picture? We'll need that for the article. Thanks,

**Comment by Baseband-processor** [comment]
Hey Brian,
I've made some photo right now, decide which size you want for the site,
for me is the same.

Regards
Edoardo Mantovani


Il giorno ven 18 set 2020 alle ore 18:51 brian d foy <
notifications@github.com> ha scritto:

**Comment by briandfoy** [comment]
@Baseband-processor send me the best resolution / largest picture you want and I'll take care of the rest. I can always crop and reduce. Sending it to my email is fine.

**Comment by Baseband-processor** [comment]
okay Brian, The maximum resolution is around 3k pixel.


Il giorno ven 18 set 2020 alle ore 19:57 brian d foy <
notifications@github.com> ha scritto:

**Comment by Baseband-processor** [comment]
Ah sorry, I had an error with the images loading
![IMG_0286-removebg](https://user-images.githubusercontent.com/68107554/93630189-db4a5780-f9e9-11ea-98d8-ef0c7276ca6e.png)

**Comment by briandfoy** [comment]
@briandfoy Can we get a picture where your hand is not over your face? As a headshot (like those you see on Perl.com), your hand would appear to come out of nowhere.

**Comment by Baseband-processor** [comment]
Unfortunately other iamges had bad resolution,  maybe tomorrow if you want I can retry

**Comment by Baseband-processor** [comment]
Hi Brian,
here the photo, you can adapt.

Regards
Edoardo Mantovani
![IMG_0295](https://user-images.githubusercontent.com/68107554/93665525-69205400-fa77-11ea-822c-c9decae25de2.JPG)

**Comment by briandfoy** [comment]
Great. We're at the final step and you have nothing more you need to do. We'll schedule your article for release sometime next week. Congrats! You're a Perl.com author now. :)

**Comment by Baseband-processor** [comment]
Many Thanks!

get ready because I have many other articles in my computer!

Regards
Edoardo Mantovani, 2020

Il giorno dom 20 set 2020 alle ore 21:40 brian d foy <
notifications@github.com> ha scritto:

**Comment by Baseband-processor** [comment]
Do you know if I am the only italian in the author list? or at least the
youngest?

Regards
Edoardo Mantovani

Il giorno dom 20 set 2020 alle ore 21:45 Edoardo Mantovani <
mantovani.edoardo18@gmail.com> ha scritto:

**Comment by briandfoy** [comment]
I've pushed the changes to make this live sometime today or tomorrow!

If you have other corrections, open a new issue or send a new pull request.

**Comment by Baseband-processor** [comment]
Hi Brian,

I'll think if it's possibile to add new contents.

Regards
Edoardo Mantovani

Il giorno giovedì 24 settembre 2020, brian d foy <notifications@github.com>
ha scritto:

**Comment by Baseband-processor** [comment]
Hi Brian,

I rewrite some parts, now the test look like this:



Since my first days studying computer security, the concept of "protocol" fascinated me. Maybe for their enormous diffusion in almost every computer system,in fact  our daily lives heavily depends from these mathematical-logical processes. As I say "trust on machines but don't trust humans", this because if machines are programmed correctly, there won't be any problems related to security, the problem comes when us write code.

Returning to us,during the quarantine I was able to find the good side of the home confination: effectively I hadn't enough time to read an entire book due to school's tests, but for my luck, I had enough time for reading one or two _Request For Comments_ (RFC) documents.

What are RFCs?
--------------

"Request For Comments" are one of the best online references for learning how networking really works internally, this guarantee a complete and an in-depth approach, which can be extremely helpfull for understanding which operations are executed in our computer daily routine.
Essentially RFCs are simply text documents which define every single standard that has been approved by the Internet Engineering Task Force (IETF). Obviously These documents are a good entry point for developing the philosophy and the main idea of the _protocol analysis_: an emerging security field which uses logic instructions and an high level of abstraction for evaluating  the security of the specified protocol.

Every RFC has a title and its associated number, for example the RFC 3607 is the "Chinese Lottery Cryptanalysis Revisited: The Internet as a Codebreaking Tool", in a more perl-ish notation this would be equal to:

```perl
my %RFC = (
  $number => $name,
);
```

The official  [IETF website](https://www.ietf.org) is a great resource for finding RFCs, but lacks some "preview" features, which complicate the documents search.

For this reason I decided to create a fast and efficient script which permits to download RFCs through a keyword and lets decide the user which document wants to read ( and  at a later time, to save ) and which ones to ignore (and delete).

My script uses [Net::RFC::Search]({{< mcpan "Net::RFC::Search" >}}) as back-end search engine, and [Term::ANSIColor]({{< mcpan "Term::ANSIColor" >}}) for the display—there will be a lot of text in the terminal and different colors can help to distinguish the various informations!.

```perl
#!/usr/bin/perl
# Made by Edoardo Mantovani in 2020

use strict;
use warnings;

use File::Path qw(make_path);
use File::Spec::Functions;
use LWP::Protocol::https; # Net::RFC::Search needs this
use Net::RFC::Search;
use Term::ANSIColor;

my $folder = shift or die "./RFC <Folder> <Query>\n";
my $query  = shift or die "./RFC <Folder> <Query>\n";

make_path $folder;

my $rfc_interface = Net::RFC::Search->new();
my @rfc_nums = $rfc_interface->search_by_header( $query );

print "RFCs [@rfc_nums]\n";

foreach my $rfc_num ( @rfc_nums ) {
  my $local_file = catfile( $folder, $rfc_num ); # i.e final folder = /tmp/1110
  if ( $rfc_interface->get_by_index( $rfc_num, $local_file ) ) {
    print colored( "Downloaded: $rfc_num\n", "green" );
    view_rfc( $local_file );
  }
  else {
    print "Error with RFC $rfc_num\n";
  }
}

sub view_rfc {
  my( $file ) = @_;

  open my $fh, '<', $file or do {
    warn "Could not open file [$file]: $!\n";
    return;
  };

  while( <$fh> ) {
  	print;
  	next unless $. == 25;
    print colored("Do you want to save this RFC? [Y/N] ", "red");
    my $input = <STDIN>;
    chomp( $input );
	unlink $file if uc($input) eq "N";
    last;
  }
}
```

Running the program requires the directory name for saving the files and a query. if the folder doesn't exists, automatically will be created one.

```
$ ./rfc_search rfcs cookie
```

I've also decided to display only the first 25 lines of each matching RFC and prompt to save it.

![](/images/searching_internet_rfcs/searching.gif)

How it works
------------

The `search_by_header` returns the RFC numbers for each of the documents that has the query word:

```perl
my @rfc_nums = $rfc_interface->search_by_header( $query );
```

Then, I fetch each document by specifying its number and local filename. I do this even if I won't keep it because I don't know what's in it yet:

```perl
$rfc_interface->get_by_index( $rfc_num, $local_file );
```

For the last part, I look at the first 25 lines of the file. I have a prompt that asks me if I want to save it. If I enter "N", I delete that file. I color the prompt so I can see it against the RFC text:

```perl
sub view_rfc {
  my( $file ) = @_;

  open my $fh, '<', $file or do {
    warn "Could not open file [$file]: $!\n";
    return;
  };

  while( <$fh> ) {
  	print;
  	next unless $. == 25;
    print colored("Do you want to save this RFC? [Y/N] ", "red");
    my $input = <STDIN>;
    chomp( $input );
    rmtree(@_) if uc($input) eq "N";
    last;
  }
}
```


Other uses and suggestions
--------------------------

I made this simple script mainly for save time and have a better interface for interacting with the RFC site, I want to recommend to see the TODO part in the [Net::RFC::Search]({{< mcpan "Net::RFC::Search" >}}) page. 
For a better script, it would be cool to implement `curl` and `lynx` to retrieve cancelled RFC's, this an optional part which could be a good exercise for extending the script. 


**resources**
- [Request for Comments: User Stories and Scenarios](https://blogs.helsinki.fi/mildred/2017/01/31/request-for-comments-user-stories-and-scenarios/)
- [Wikipedia's RFC entry](https://en.wikipedia.org/wiki/Request_for_Comments)

**Comment by briandfoy** [comment]
Okay, I've unpublished the article for now so I can deal with these changes. I don't know when I'll have time to do that just yet.

And, this is not a good way to interact. After asking you for weeks for such changes, you didn't supply any. The night after I schedule it to be published, you want changes that you paste into a comment. That's a lot of work you're creating for me. It would really help if you could send these as pull requests so I can easily see the diffs.

**Comment by Baseband-processor** [comment]
Yeah sorry but I ahde a lot of works to do

Il giorno gio 24 set 2020 alle ore 16:18 brian d foy <
notifications@github.com> ha scritto:

**Comment by Baseband-processor** [comment]
I had a lot of works to do in those days, I had no times for an in-depth
correction

Il giorno gio 24 set 2020 alle ore 16:21 Edoardo Mantovani <
mantovani.edoardo18@gmail.com> ha scritto:

**Comment by Baseband-processor** [comment]
I've proposed the changes in the article, check if is arrived.

Il giorno gio 24 set 2020 alle ore 16:23 Edoardo Mantovani <
mantovani.edoardo18@gmail.com> ha scritto:

**Comment by briandfoy** [comment]
This is now published
